version: "3.9"
services:
  # === Infra ===
  orders:
    build: .
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200
      SERVER_PORT: 8080
    ports: ["8080:8080"]
    depends_on: [redpanda, elasticsearch]


  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    command:
      - redpanda start --overprovisioned --smp 1 --memory 512M --reserve-memory 0M --node-id 0 --check=false
    ports: ["9092:9092"]
    environment:
      KAFKA_BROKERS: redpanda:9092

  loki:
    image: grafana/loki:2.9.4
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports: [ "3100:3100" ]

  promtail:
    image: grafana/promtail:2.9.4
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml
    command: [ "--config.file=/etc/promtail/config.yml" ]
    depends_on: [ loki ]

  grafana:
    image: grafana/grafana:11.0.0
    ports: [ "3000:3000" ]
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
    depends_on: [ loki ]


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports: ["9200:9200"]

  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: orders
    ports: [ "5432:5432" ]


  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_SECURITY_ENABLED=false
    ports: ["5601:5601"]
    depends_on: [elasticsearch]

    # === Services ===
  orders-service:
    build: ./orders-service
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/orders
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SERVER_PORT: 8080
    ports: [ "8080:8080" ]
    depends_on: [ redpanda, postgres ]

  indexer-service:
    build: ./indexer-service
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200
      SERVER_PORT: 8081
    ports: [ "8081:8081" ]
    depends_on: [ redpanda, elasticsearch ]