version: "3.9"
services:
  orders:
    build: .
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200
      SERVER_PORT: 8080
    ports: ["8080:8080"]
    depends_on: [redpanda, elasticsearch]


  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    command:
      - redpanda start --overprovisioned --smp 1 --memory 512M --reserve-memory 0M --node-id 0 --check=false
    ports: ["9092:9092"]
    environment:
      KAFKA_BROKERS: redpanda:9092


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports: ["9200:9200"]


  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_SECURITY_ENABLED=false
    ports: ["5601:5601"]
    depends_on: [elasticsearch]